sendmail: add code for running send-queue, remove debug output

diff --git a/sendmail b/sendmail
--- a/sendmail
+++ b/sendmail
@@ -179,8 +179,6 @@ resolve_aliases()
 
 # Mail errors to sender by default
 MAIL_ERRORS=1
-# Don't deliver to sender, if the sender address is found after alias expansion
-SEND_TO_SELF=0
 FIRSTREC=""
 while PAR="$1"; shift ; do
     case $PAR in 
@@ -292,20 +290,18 @@ else
     MARG="forward"
 fi
 
-echo "MARG: $MARG"
+#echo "MARG: $MARG"
 
-#echo "/// Starting delivery ///"
-# Local delivery
-#echo "LOC_RECV: |${LOC_RECV}|" 
+# Local delivery loop
 LOCAL_SENT=""
 INET_RECV=""
-#ALIST=$LOC_RECV
+FORWARDERS=""
 ALIST=$RECIPIENTS
 while [ -n "$ALIST" ]; do 
     A=${ALIST%%,*} 
     ALIST=$(cdr "$ALIST")
-    echo "A1: $A"
-    echo "ALIST1: $ALIST"
+#    echo "A1: $A"
+#    echo "ALIST1: $ALIST"
     R=${A%%@localhost*}
     R=${R%%@$HOSTNAME}
     case $R in
@@ -314,36 +310,58 @@ while [ -n "$ALIST" ]; do
             continue ;;
         *)
             resolve_aliases $R
-            ALIST=$(append "$AL_LOCLIST" "$ALIST") ;;
+            if [ "$R" != "$AL_LOCLIST" ] ; then 
+                ALIST=$(append "$AL_LOCLIST" "$ALIST")
+                continue
+            fi ;;
     esac
-    A=${ALIST%%,*}
-    ALIST=$(cdr "$ALIST")
-    echo "A2: $A"
-    echo "ALIST2: $ALIST"
-    echo "sending: $A"
-    if check_username "$A" ; then
+    if check_username "$R" ; then
         true
     else
         continue
     fi
-    if contains "$LOCAL_SENT" "$A" ; then
+    if contains "$LOCAL_SENT" "$R" ; then
         continue
     fi
-    FLIST=$(cat $TEMPF | $MMDA $MARG $A | sed -n '1h;1!H;${;g;s/\n/, /g;p;}')
-    echo "FLIST: $FLIST"
+#    echo "sending: $R"
+    FLIST=$(cat $TEMPF | $MMDA $MARG $R | sed -n '1h;1!H;${;g;s/\n/,/g;p;}')
+#    echo "FLIST: $FLIST"
     ALIST=$(append "$FLIST" "$ALIST")
-    LOCAL_SENT=$(append "$LOCAL_SENT" "$A")
+    LOCAL_SENT=$(append "$LOCAL_SENT" "$R")
+    if [ "$SEND_INET" != "0" ] ; then
+        FORWARDERS=$(append "$FORWARDERS" "$R")
+    fi
 done
 
-echo "INET_RECV: $INET_RECV"
+#echo "INET_RECV: $INET_RECV"
+#echo "FORWARDERS: $FORWARDERS"
+
+#FIXME: Check if we're online?
 
 # Do internet delivery
 if [ $SEND_INET = "0" ] ; then
     QARGS=$(echo $INET_RECV | sed 's/, / /g')
-    echo $QARGS
+#    echo $QARGS
 #    cat $TEMPF | $QUEUEMAIL $QARGS
+#    $SENDQUEUE
+else
+    if [ -n "$INET_RECV" ] ; then
+        echo "Warning: Could not send to following external addresses:" >&2
+        echo "$INET_RECV" | tr ',' '\n' >&2  
+    fi
+    # Run outgoing queues from people who were sent mail
+#    ALIST=$FORWARDERS
+#    while [ -n "$FORWARDERS" ] ; do
+#        A=${ALIST%%,*} 
+#        ALIST=$(cdr "$ALIST")
+#        $MMDA send $A &        
+#    done
 fi
 
-echo "sent to: $LOCAL_SENT"
-#echo "inet to: $INET_FWDS"
+#echo "sent to: $LOCAL_SENT"
+#echo "inet to: $INET_RECV"
 rm -f $TEMPF
+
+#read
+
+exit 0
