Add functions for error logging and use them.
complain(): Take a message and print it to stderr and log to syslog.

die(): Take an exit code and message, complain() the message and
exit with the code.

diff --git a/sendmail.in b/sendmail.in
--- a/sendmail.in
+++ b/sendmail.in
@@ -11,6 +11,25 @@ PINGHOST="www.google.com"
 PWFILE="/etc/passwd"
 ALIASFILE="/etc/aliases"
 
+
+# complain $MESSAGE
+# Print and log a string
+complain ()
+{
+    logger -t mmta $1
+    echo $1 >&2
+}
+
+
+# die $EXITCODE $MESSAGE
+# Print and log a message and exit
+die () {
+    complain $2
+    complain "Exiting with code $1"
+    exit $1
+}
+
+
 is_online ()
 {
     ping -c 1 -w 2 $PINGHOST > /dev/null 2>&1
@@ -155,7 +174,7 @@ resolve_aliases()
         A=${ALIST%%,*}
         ALIST=$(cdr "$ALIST")
         if contains "$PROCESSED" "$A" ; then
-            echo "Warning: aliases file has a loop with user $A" 1>&2
+            complain "Warning: aliases file has a loop with user $A"
             continue
         fi
         case "$A" in
@@ -195,8 +214,7 @@ find_script ()
     elif [ -x "$SYSCONFDIR/$1" ] ; then
         eval "$2=$SYSCONFDIR/$1"
     else
-        echo "Could not find script $1" >&2
-        exit 1
+        die 1 "Could not find script $1"
     fi
 }
 
@@ -292,7 +310,7 @@ while [ $# -gt 0 ] ; do
             shift
             break 2 ;;
         -*)
-            echo "Warning: Ignoring unknown parameter $PAR" 1>&2 ;;
+            complain "Warning: Ignoring unknown parameter $PAR" ;;
         *) # Already at first recipient
             break 2 ;;
     esac
@@ -383,8 +401,7 @@ if [ "$SEND_INET" = "0" ] ; then
     fi
 else
     if [ -n "$INET_RECV" ] ; then
-        echo "Warning: Could not send to following external addresses:" >&2
-        echo "$INET_RECV" | tr ',' '\n' >&2
+        complain "Warning: Could not send to following external addresses: $INET_RECV"
     fi
     if is_online ; then
         # Run outgoing queues from people who were sent mail
