sendmail: Use die() when not able to create a temp file.

diff --git a/sendmail.in b/sendmail.in
--- a/sendmail.in
+++ b/sendmail.in
@@ -322,10 +322,7 @@ for PAR in $@ ; do
 done
 
 TEMPF=$(tempfile)
-if [ "$?" != "0" ] ; then
-    echo "Could not create a temporary file"
-    return 1
-fi
+[ "$?" = "0" ] || die 1 "Could not create a temporary file"
 
 cat >> $TEMPF
 
